server:
  port: 8672

spring:
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  instance:
    hostname: peer2  # 配置中心 , peer2 配置在hosts文件里
    instance-id: ${spring.application.name}-${server.port}  #服务实例在注册中心的名字
    ip-address: 127.0.0.1
  client:
    # 表示是否注册自身到eureka服务器
    register-with-eureka: false
    # 是否从eureka上获取注册信息
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7861/eureka

  server:
    enable-self-preservation: off
    batch-replication: true
    peerEurekaNodesUpdateIntervalMs: 1